const data = [
  {
    id: 0,
    name: "Zen Go Synergy Core",
    price: 599,
    price_old: 699,
    currency: "&euro;",
    instock: 10,
    category: "Audio",
    thumb: "/assets/images/product-1.png",
    badge: "Special Offer",
    url: "#",
  },
  {
    id: 1,
    name: "Zen Tour",
    price: 2999,
    price_old: 3999,
    currency: "&euro;",
    instock: 10,
    category: "Audio",
    thumb: "/assets/images/product-2.png",
    badge: "Special Offer",
    url: "#",
  },
  {
    id: 2,
    name: "Galaxy 32",
    price: 5999,
    price_old: 6999,
    currency: "&euro;",
    instock: 10,
    category: "Audio",
    thumb: "/assets/images/product-3.png",
    badge: "Special Offer",
    url: "#",
  },
  {
    id: 3,
    name: "Galaxy 64",
    price: 10999,
    price_old: 11999,
    currency: "&euro;",
    instock: 10,
    category: "Audio",
    thumb: "/assets/images/product-4.png",
    badge: "Special Offer",
    url: "#",
  },
  {
    id: 4,
    name: "Orion Studio Synergy Core",
    price: 3999,
    price_old: 4999,
    currency: "&euro;",
    instock: 10,
    category: "Audio",
    thumb: "/assets/images/product-5.png",
    badge: "Special Offer",
    url: "#",
  },
  {
    id: 5,
    name: "Discrete 8 Pro",
    price: 3999,
    price_old: 4999,
    currency: "&euro;",
    instock: 10,
    category: "Audio",
    thumb: "/assets/images/product-6.png",
    badge: "Special Offer",
    url: "#",
  },
];
